# pyproject.toml

[build-system]
requires = ["setuptools>=49.6.0", "wheel>=0.36.2"]
build-backend = "setuptools.build_meta"

[tool.build-system]
requires = ["setuptools>=49.6.0", "wheel>=0.36.2"]
build-backend = "setuptools.build_meta"
