# .github/workflows/test_and_publish.yml

name: Test and Publish

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
        pip install pyinputplus

    - name: Run tests
      working-directory: src
      run: python tea.py

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
        pip install twine

    - name: Build and publish to Test PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi-AgENdGVzdC5weXBpLm9yZwIkMWYxZTE3OTYtMjc5OC00N2VhLWJmNWYtNjg2OTQ5ODEwNGRjAAIqWzMsIjRmZTQ1YjRkLWRjZWYtNGJiOS05OWM0LTU1ZDJlMjVkZGI0NyJdAAAGIHla2ZMGt8_wMNZmtcGYk4ZZ0qrDtV_AX6FzJxanhQx5 }}
      run: |
        rm -rf dist/
        python -m build --sdist --wheel -o dist/
        twine upload --repository testpypi dist/*
