name: Test and Publish

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
        pip install pyinputplus

    - name: Run tests
      working-directory: src
      run: python teakiandra.py

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          pip install twine

      - name: Check if version exists
        run: |
          if twine check --repository-url https://test.pypi.org/legacy/ dist/*; then
            echo "Package already published, skipping upload."
            exit 0
          fi

      - name: Build and publish to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build --sdist --wheel -o dist/
          twine upload --repository testpypi dist/*
