# .github/workflows/test_and_publish.yml

name: Test and Publish

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          pip install pyinputplus

      - name: Run tests
        working-directory: src
        run: python tea.py

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          pip install twine

      - name: Check if already published
        id: check_publish
        run: echo ::set-output name=published::$(if [ -f "published_flag" ]; then echo "true"; else echo "false"; fi)

      - name: Build and publish to Test PyPI
        if: steps.check_publish.outputs.published != 'true'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          cd src
          python -m build
          twine upload --repository testpypi dist/*
          echo "true" > published_flag  # Create a flag indicating that the package has been published
