name: Test and Publish

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          pip install pyinputplus

      - name: Run tests
        working-directory: src
        run: python teakiandra.py

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          pip install twine

      - name: Check if version has changed
        id: check_version
        run: |
          current_version=$(python -c "import teakiandra; print(teakiandra.__version__)")
          previous_version=$(git describe --abbrev=0 --tags)
          echo "Current version: $current_version"
          echo "Previous version: $previous_version"
          if [ "$current_version" = "$previous_version" ]; then
            echo "No version change. Skipping publish."
            exit 1
          fi
        continue-on-error: true

      - name: Build and publish to Test PyPI
        if: steps.check_version.outcome == 'success'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build
          twine upload --repository testpypi dist/*
